apiVersion: cilium.io/v2
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: host-firewall-egress-to-fqdns-{{trimSuffix .ExternalTarget "."}}
spec:
  nodeSelector: {}
  egress:
  - toPorts:
    - ports:
      - port: "80"
        protocol: TCP
    toFQDNs:
    - matchName: "{{.ExternalTarget}}"
  - toPorts:
    - ports:
      - port: "53"
        protocol: UDP
      - port: "53"
        protocol: TCP
      rules:
        dns:
        - matchPattern: "*"
    toEntities:
    - world
  - toEntities:
    - health
    - kube-apiserver
    - remote-node
